# Generated by Django 6.0.7 on 2026-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_image_remove_restaurant_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
