# Generated by Django 6.0.7 on 2026-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss (Calorie Deficit)'), ('maintenance', 'Maintain Weight & Balance'), ('weight_gain', 'Weight Gain & Muscle Mass')], default='weight_loss', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='protein_target',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
