# Generated by Django 6.0.7 on 2026-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_daily_calorie_goal_user_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
