# Generated by Django 6.0.7 on 2026-07-29 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0002_remove_restaurant_image_remove_restaurant_is_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='diet_goals',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='nutrition_score',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sugar',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_name',
            field=models.CharField(default='Sample Food', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant'),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='DietGoal',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
